// Generated by CoffeeScript 1.9.1
(function() {
  $(document).ready(function() {
    var force, height, link, links, node, nodes, svg, width;
    width = 640;
    height = 480;
    nodes = [
      {
        x: width / 3,
        y: height / 2
      }, {
        x: 2 * width / 3,
        y: height / 2
      }
    ];
    links = [
      {
        source: 0,
        target: 1
      }
    ];
    svg = d3.select('body').append('svg').attr('width', width).attr('height', height);
    force = d3.layout.force().size([width, height]).nodes(nodes).links(links);
    force.linkDistance(width / 2);
    link = svg.selectAll('.link').data(links).enter().append('line').attr('class', 'link');
    node = svg.selectAll('.node').data(nodes).enter().append('circle').attr('class', 'node');
    force.on('tick', function() {
      node.attr('r', width / 25).attr('cx', function(d) {
        return d.x;
      }).attr('cy', function(d) {
        return d.y;
      });
      return link.attr('x1', function(d) {
        return d.source.x;
      }).attr('y1', function(d) {
        return d.source.y;
      }).attr('x2', function(d) {
        return d.target.x;
      }).attr('y2', function(d) {
        return d.target.y;
      });
    });
    return force.start();
  });

}).call(this);
