// Generated by CoffeeScript 1.10.0
(function() {
  var By, CHANNEL, PASSWORD, USERNAME, driver, selenium;

  selenium = require('selenium-webdriver');

  By = selenium.By;

  USERNAME = process.argv[2];

  PASSWORD = process.argv[3];

  CHANNEL = process.argv[4];

  console.log("Starting driver for channel " + CHANNEL + " using " + USERNAME + "//" + PASSWORD);

  driver = new selenium.Builder().withCapabilities(selenium.Capabilities.chrome()).build();

  driver.getWindowHandle();

  driver.get(CHANNEL).then(function() {
    return driver.findElement(By.css('#header_login'));
  }).then(function(element) {
    return element.click();
  }).then(function() {
    return driver.sleep(5000);
  }).then(function() {
    return driver.getWindowHandle();
  }).then(function(handle) {
    return driver.sleep(5000);
  }).then(function() {
    return driver.switchTo().frame(0);
  }).then(function() {
    return driver.sleep(5000);
  }).then(function() {
    return driver.findElement(By.css('input[name=username]'));
  }).then(function(username) {
    return username.sendKeys(USERNAME);
  }).then(function() {
    return driver.findElement(By.css('input[name=password]'));
  }).then(function(password) {
    return password.sendKeys(PASSWORD);
  }).then(function() {
    return driver.findElement(By.css('input[type=submit]'));
  }).then(function(submit) {
    return submit.click();
  }).then(function() {
    return driver.sleep(5000);
  }).then(function() {
    return driver.switchTo().defaultContent();
  }).then(function() {
    return driver.sleep(1 * 60 * 1000);
  }).then(function() {
    return driver.quit();
  });

}).call(this);
